PROGRAM TO DEMONSTRATE ALL  ARITHMETIC OPERATORS

public class Hey{
    public static void main(String[]args){
        //arithmetic operators
        int num1=29;
        int num2=30;
        int ADD=num1+num2;
        int SUB=num1-num2;
        int MUL= num1*num2;
        int DIV=num1/num2;
        int MOD=num1%num2;
        System.out.println("ADDITION of 2 nos:"+ADD);
        System.out.println("SUBTRACTION of 2 nos:"+SUB);
        System.out.println("PRODUCT of 2 nos:"+MUL);
        System.out.println("DIVISION of 2 nos:"+DIV);
        System.out.println("remainder of 2 nos:"+MOD);
    }
}
